### ISSUE TITLE
Running cpplint on Windows 10 cmd.exe results in "failed to create process"

### ISSUE THREAD

**Issue by johnthagen** [theandrewdavis/cpplint#1]
The `cpplint` console entry point (`cpplint.exe`) does not seem to be working on Windows 10 with Python 3.5.

```bat
>python -m venv venv
>cd venv
>Scripts\activate.bat
(venv) >python -V
Python 3.5.1
(venv) >pip install cpplint
Collecting cpplint
  Using cached cpplint-0.0.6.tar.gz
Installing collected packages: cpplint
  Running setup.py install for cpplint
Successfully installed cpplint-0.0.6
(venv) >cpplint
failed to create process.
```

The same behavior happens outside of a `venv`.

**Comment by johnthagen** [comment]
For a comparison point, ``cpplint_junit`` does successfully execute in the same `venv`.

**Comment by johnthagen** [comment]
The host OS is Windows 10 Pro x64.

The working directory path used in the above example contains a space:

`(venv) C:\Users\John Hagen\Desktop\venv>`

The path to `python` also contains a space:

```bat
(venv) C:\Users\John Hagen\Desktop\venv>where.exe python
C:\Users\John Hagen\Desktop\venv\Scripts\python.exe
C:\Users\John Hagen\AppData\Local\Programs\Python\Python35\python.exe
```

Running `cpplint` from a path without spaces results in the same error:

```bat
C:\Users>cpplint
failed to create process.
```

**Comment by johnthagen** [comment]
I just tried it on another PC (Windows 10 *Home* x64) and had the same issue.  For what it's worth, this computer was upgraded from Windows 7 to Windows 10, as opposed to the first PC which was a clean Windows 10 install.

**Comment by johnthagen** [comment]
@theandrewdavis Pretty sure this is a `pip` problem and has nothing to do with `cpplint` specifically.  You can probably close this issue.

- https://github.com/pypa/pip/issues/923
- https://github.com/pypa/pip/issues/2783
- https://bitbucket.org/pypa/setuptools/issues/398/removal-of-escaping-in-shebang-in

**Comment by johnthagen** [comment]
A current work around is to install with the legacy `easy_install` command, which does work correctly on Windows with a space in the path:

`easy_install cpplint`

**Comment by theandrewdavis** [comment]
Thanks for tracking this down for me @johnthagen. I too was able to reproduce the problem using an username with a space and could work around it with easy_install, so I agree its a pip issue and am closing.
