### ISSUE TITLE
Please merge with main branch to enable style check on .cu and .cuh files

### ISSUE THREAD

**Issue by jasjuang** [theandrewdavis/cpplint#9]
Is it possible to update the cpplint.py from google (the main branch)? I am mainly looking for the style check feature on cuda source and header files (.cu and .cuh). Will be awesome to see this in the cpplint for pip install.

**Comment by theandrewdavis** [comment]
This took me a bit to figure out, but cuda source and header files should already be valid extensions in this version. A while back the former maintainer made [a change](https://github.com/theandrewdavis/cpplint/commit/f5e427c89b15d4551738d8e39807e3cf782cbc84) to make the file extensions cpplint checks more flexible. Now you can pass them in at the command line to add or remove more. The default extensions supported haven't changed, though, as far as I can tell. `.cu` and `.cuh` are in the list! So I'm thinking there's something else going on if cuda files aren't working for you.

Does that help? I'm happy to investigate further if you have more problems

**Comment by jasjuang** [comment]
First I do sudo pip install cpplint --upgrade 

Suppose I have test.cuh

// Copyright 2016 jasjuang

#ifndef WRONG_PATH_H_
#define WRONG_PATH_H_

class test{
 public:
   //something
};

#endif  // WRONG_PATH_H_

If I do cpplint test.cuh

Ignoring test.cuh; not a valid file name (c, h++, cc, h, hpp, c++, cxx, cpp, hxx)
Done processing test.cuh
Total errors found: 0

so the .cuh file is not in the default file list, could you look into this? 

I have to do cpplint --extensions=cuh test.cuh
Done processing test.cuh
Total errors found: 0

but even doing this it is not showing the  "#ifndef header guard has wrong style, please use: CORRECT_PATH_H_  [build/header_guard] [5]" error if the test.cuh is renamed to test.h. Please help, thanks!

**Comment by jasjuang** [comment]
Actually I figured out this problem is also there in the official cpplint repo. I already reported https://github.com/google/styleguide/issues/113. Would be awesome if you can suggest any workaround.

**Comment by theandrewdavis** [comment]
Not sure what I was thinking when I said above that `.cuh` and `.cu` are in the list, the definitely aren't! I'm adding a change to make cpplint recognize these file extensions by default (in line with the docs) and to recognize `.cuh` files as headers. If this doesn't solve your issue, let me know!

**Comment by jasjuang** [comment]
This solves all my problem! Could update the pip install cpplint to reflect this awesome update?

**Comment by theandrewdavis** [comment]
Sure, version 1.2.1 is published and has these changes
